using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ScriptCoreLib;
using java.lang.annotation;

namespace ScriptCoreLibJava.BCLImplementation.System.ServiceModel
{
    // https://msdn.microsoft.com/en-us/library/system.servicemodel.messagecontractattribute(v=vs.110).aspx


    // C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.ServiceModel.dll
    // 

    //[Script(Implements = typeof(global::System.ServiceModel.ClientBase))]
    [Script(ImplementsViaAssemblyQualifiedName = "System.ServiceModel.MessageContractAttribute")]
    //public class __MessageContractAttribute  : ScriptCoreLib.Shared.BCLImplementation.System.__Attribute
    public class __MessageContractAttribute : Attribute
    {
        // can we use the attribute generated by wsdl codegen?

        //Attribute

        public string WrapperName { get; set; }

        // need to keep em as properties, jsc has to translate them to annotation fields.
        // Z:\jsc.svn\examples\java\hybrid\Test\TestMessageContractAttribute\TestMessageContractAttribute\Program.cs
        public string WrapperNamespace { get; set; }
        // error: annotation __MessageContract is missing value for the attribute _WrapperNamespace_k__BackingField

        public bool IsWrapped { get; set; }
    }

    //[java.lang.annotation.DocumentedAttribute()]
    // 

    //Z:\jsc.svn\examples\java\TestAttribute\TestAttribute\Class1.cs

    //[Script]
    ////public interface __MessageContract : java.lang.annotation.Annotation
    //public interface __MessageContract : Annotation
    //{
    //    // Do we need it? Why wont jsc infer it ?
    //}

}
